steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/graphql-portfolio", "."]
    # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/graphql-portfolio"]
    # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "graphql-portfolio",
        "--image",
        "gcr.io/$PROJECT_ID/graphql-portfolio",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--update-env-vars",
        "GITHUB_TOKEN=${_GITHUB_TOKEN}",
      ]
images:
  - gcr.io/$PROJECT_ID/graphql-portfolio
